Repository nnstreamer/nnstreamer, pull requests merged in 2018-10, with the labels that each got.

#687 [Filter/Custom] remove unnecessary flag
  include/tensor_filter_custom.h
Labels: Hacktoberfest

#691 [Tensor Decoder] Security: fixed not null termination of strncpy(3)
  gst/tensor_decoder/tensordec.c
Labels: Hacktoberfest, bug

#697 [Common] fix coverity issue 1035367
  gst/nnstreamer/tensor_common.c
Labels: Hacktoberfest, bug

#677 [Example/OpenCV] Add OpenCV custom filter example
  debian/control
  nnstreamer_example/CMakeLists.txt
  nnstreamer_example/custom_example_opencv/CMakeLists.txt
  nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_scaler.cc
  packaging/nnstreamer.spec
  tests/nnstreamer_filter_custom/runTest.sh
Labels: Hacktoberfest

#709 [PkgConfig] Use @INCLUDE_INSTALL_DIR@ instead of the hard-coded path
  nnstreamer.pc.in
Labels: Hacktoberfest, minor bug

#701 [Filter/TFLite] remove memcpy after invoke
  gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
Labels: Hacktoberfest

#669 [TensorMerge] Add Synchronization based on PTS Time
  gst/tensor_merge/gsttensormerge.c
  gst/tensor_merge/gsttensormerge.h
Labels: Hacktoberfest
