Repository nnstreamer/nnstreamer, pull requests merged in 2018-11, with the labels that each got.

#680 [TensorMux] Add Synchronization based on PTS Time with synch option
  gst/tensor_mux/gsttensormux.c
  gst/tensor_mux/gsttensormux.h
  tests/nnstreamer_demux/runTest.sh
  tests/nnstreamer_sink/unittest_sink.cpp
Labels: Hacktoberfest

#679 [TensorMerge] Add Time Synchronization Option
  gst/tensor_merge/gsttensormerge.c
  gst/tensor_merge/gsttensormerge.h
Labels: Hacktoberfest

#681 [TensorMerge] Add Test case for time synchronization
  tests/nnstreamer_converter/generateGoldenTestResult.py
  tests/nnstreamer_merge/runTest.sh
Labels: Hacktoberfest

#682 [TensorMux] Add time synchronization test case @open sesame 11/02 16:45
  tests/nnstreamer_mux/runTest.sh
Labels: Hacktoberfest

#729 Migration of gst-launch testcases to SSAT @open sesame 11/02 17:37
  packaging/nnstreamer.spec
  tests/nnstreamer_converter/runTest.sh
  tests/nnstreamer_decoder/runTest.sh
  tests/nnstreamer_decoder_image_labeling/runTest.sh
  tests/nnstreamer_demux/runTest.sh
  tests/nnstreamer_filter_custom/runTest.sh
  tests/nnstreamer_filter_tensorflow_lite/runTest.sh
  tests/nnstreamer_merge/runTest.sh
  tests/nnstreamer_mux/runTest.sh
  tests/nnstreamer_split/runTest.sh
  tests/nnstreamer_tensors/runTest.sh
  tests/testAPI.sh
  tests/testAll.sh
  tests/transform_arithmetic/runTest.sh
  tests/transform_dimchg/runTest.sh
  tests/transform_stand/runTest.sh
  tests/transform_typecast/runTest.sh
Labels: CI

#704 [Example/OpenCV] Add OpenCV custom filter example: Average
  nnstreamer_example/custom_example_opencv/CMakeLists.txt
  nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_average.cc
  tests/nnstreamer_filter_custom/runTest.sh
Labels: Hacktoberfest

#765 [Emergency Fix] Build Error Fix / tensor-dec @open sesame 11/05 11:14
  gst/tensor_decoder/tensordec.h
Labels: RELEASE CRITICAL, bug

#754 [Testcase] Recurrent Network, Input Stream @open sesame 11/02 17:47
  tests/recurrent_pipeline/generateTestCase.py
  tests/recurrent_pipeline/runTest.sh
Labels: PR/Ready2Go

#756 [Example] Custom filter, "dummy LSTM", added @open sesame 11/04 15:05
  nnstreamer_example/CMakeLists.txt
  nnstreamer_example/custom_example_LSTM/CMakeLists.txt
  nnstreamer_example/custom_example_LSTM/dummy_LSTM.c
Labels: PR/Ready2Go

#799 [Decoder/direct_video] Pipeline may allocate buffer for you already @open sesame 11/14 16:02
  gst/tensor_decoder/tensordec-directvideo.c
  gst/tensor_decoder/tensordec.c
Labels: PR/Ready2Go

#843 [Filter/TFLite] fix bug
  gst/tensor_filter/tensor_filter_tensorflow_lite.c
  gst/tensor_filter/tensor_filter_tensorflow_lite_core.cc
  gst/tensor_filter/tensor_filter_tensorflow_lite_core.h
Labels: bug

#831 [Meson] Initial commit of meson build
  gst/nnstreamer/meson.build
  gst/tensor_aggregator/meson.build
  gst/tensor_converter/meson.build
  gst/tensor_decoder/meson.build
  gst/tensor_demux/meson.build
  gst/tensor_filter/meson.build
  gst/tensor_merge/meson.build
  gst/tensor_mux/meson.build
  gst/tensor_saveload/meson.build
  gst/tensor_sink/meson.build
  gst/tensor_split/meson.build
  gst/tensor_transform/meson.build
  meson.build
Labels: PR/Ready2Go

#913 [Filter/CMAKE] Remove unnecessary message printing out @open sesame 11/26 19:49
  gst/tensor_filter/CMakeLists.txt
Labels: CI, build

#926 [DummyLSTM] Add Dummy LSTM custom example - @open sesame 11/29 14:22
  nnstreamer_example/CMakeLists.txt
  nnstreamer_example/custom_example_LSTM/CMakeLists.txt
  nnstreamer_example/custom_example_LSTM/dummy_LSTM.c
Labels: DO NOT MERGE
