Repository nnstreamer/nnstreamer, pull requests merged in 2019-10, with the labels that each got.

#1710 [Android/Test] tc fail case
  api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
Labels: PR/Ready2Go

#1706 Release of nnstreamer 1.0.0 (1.0 RC2) @open sesame 9/30 13:28
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#1735 [API/Tizen] Remove version number from libcapi-nnstreamer.so @open sesame 10/07 18:53
  api/capi/meson.build
  debian/nnstreamer-dev.install
  debian/nnstreamer.install
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1736 [Tizen/Api] fix invalid params to parse mm info
  api/capi/src/nnstreamer-capi-tizen.c
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1722 [Api/Tizen] Tizen internal API to construct pipeline
  api/capi/include/nnstreamer-capi-private.h
  api/capi/include/nnstreamer-tizen-internal.h
  api/capi/meson.build
  api/capi/src/nnstreamer-capi-pipeline.c
  packaging/nnstreamer.spec
  tests/tizen_capi/unittest_tizen_capi.cpp
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1741 [Api/Tizen] update restricted elements
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1742 [Api/Tizen] bug-fix to replace str
  api/capi/src/nnstreamer-capi-pipeline.c
  api/capi/src/nnstreamer-capi-tizen.c
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1744 [Api/Tizen] remove code which occurs error
  api/capi/src/nnstreamer-capi-tizen.c
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1752 [API/Tizen] Fix the rootstrap buildbreak issue
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1755 [Doc] Guide: writing a new tensor-filter subplugin
  Documentation/component-description.md
  Documentation/writing-subplugin-tensor-filter.md
Labels: RELEASE CRITICAL, Tizen 5.5 M2, VoC

#1749 [Api/Tizen] handle dpm restriction case
  api/capi/meson.build
  api/capi/src/nnstreamer-capi-pipeline.c
  api/capi/src/nnstreamer-capi-tizen.c
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1760 [Security] check buffer size
  api/capi/src/nnstreamer-capi-single.c
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1761 [Security] cond to compare strings
  api/capi/src/nnstreamer-capi-pipeline.c
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  ext/nnstreamer/tensor_filter/tensor_filter_python.c
  ext/nnstreamer/tensor_filter/tensor_filter_pytorch.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
  gst/nnstreamer/nnstreamer_conf.c
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_merge/gsttensormerge.c
  gst/nnstreamer/tensor_source/tensor_src_iio.c
Labels: RELEASE CRITICAL, Tizen 5.5 M2

#1756 [Doc] Tizen Native App Guide
  Documentation/getting-started.md
  Documentation/writing-tizen-native-apps.md
Labels: VoC

#1779 [CodeClean]remove duplicates in TFLiteCore::getTensorDim
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
Labels: Hacktoberfest

#1785 [single] Added API and skeleton for flexible input dimension
  api/capi/include/nnstreamer-single.h
  api/capi/src/nnstreamer-capi-single-new.c
  api/capi/src/nnstreamer-capi-single.c
Labels: Tizen 6.0 M1

#1790 [TF-Lite] Added setInputDimension
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
  gst/nnstreamer/nnstreamer_plugin_api.h
  gst/nnstreamer/tensor_common.c
Labels: Tizen 6.0 M1

#1771 [Filter] Enable C++ subplugin build @open sesame 10/18 16:07
  debian/control
  debian/nnstreamer-cpp-dev.install
  debian/nnstreamer-cpp.install
  debian/nnstreamer-dev.install
  ext/nnstreamer/tensor_filter/meson.build
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.h
  meson_options.txt
  packaging/nnstreamer.spec
Labels: Tizen 6.0 M1

#1787 [single] Implementation of flexible input dimension
  api/capi/include/tensor_filter_single.h
  api/capi/src/nnstreamer-capi-single-new.c
  api/capi/src/tensor_filter_single.c
  tests/tizen_capi/unittest_tizen_capi.cpp
Labels: Tizen 6.0 M1

#1802 [single] simplify get_tensors_info in single API @open sesame 10/22 11:55
  api/capi/src/nnstreamer-capi-single-new.c
  api/capi/src/nnstreamer-capi-single.c
Labels: RELEASE CRITICAL, Tizen 6.0 M1

#1820 [single] Fix possible svace issue later
  api/capi/src/nnstreamer-capi-single-new.c
Labels: Tizen 6.0 M1

#1803 [single] unittest for flexible dimension with tflite @open sesame 10/21 17:02
  api/capi/include/tensor_filter_single.h
  api/capi/src/nnstreamer-capi-single-new.c
  api/capi/src/tensor_filter_single.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
  tests/test_models/models/add.tflite
  tests/tizen_capi/unittest_tizen_capi.cpp
Labels: Tizen 6.0 M1

#1806 [single] More inline functions for flexible dimensions
  api/capi/include/nnstreamer-single.h
Labels: Tizen 6.0 M1

#1788 [C-API/Doc] upload the first version of guide doc
  Documentation/media/input-selector.png
  Documentation/media/output-selector.png
  Documentation/nnstreamer_capi.md
Labels: PR/Ready2Go, Tizen 5.5 M2

#1784 [Doc] Guide: how to write .NET Application
  Documentation/writing-tizen-csharp-apps.md
Labels: PR/Ready2Go, Tizen 5.5 M2
