Repository nnstreamer/nnstreamer, pull requests merged in 2019-11, with the labels that each got.

#1825 [Filter/Custom-Easy-C] Prototype of Custom-Easy Tensor Function
  gst/nnstreamer/tensor_filter_custom_easy.h
Labels: PR/Ready2Go

#1819 [nnfw] Adding nnfw base test for verification @open sesame 11/4 14:51
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  tests/meson.build
  tests/test_models/models/metadata/MANIFEST
  tests/tizen_nnfw_runtime/meson.build
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cpp
Labels: Tizen 6.0 M1

#1842 [filter/nnfw] Unittest for invoke
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cpp
Labels: Tizen 6.0 M1

#1841 [C-API] Remove unnecessary asterisk on header file - @open sesame 11/11 17:31
  api/capi/doc/nnstreamer_doc.h
  api/capi/include/nnstreamer-single.h
  api/capi/include/nnstreamer.h
Labels: PR/Ready2Go

#1870 [C-Api] fix invalid sink handle @open sesame 11/15 15:55
  api/capi/src/nnstreamer-capi-pipeline.c
  tests/tizen_capi/unittest_tizen_capi.cpp
Labels: Tizen 5.5 M2

#1847 [tensor_filter/tflite] Update for supporting various accelerators @open sesame 11/15 15:35
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.h
  gst/nnstreamer/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  tests/nnstreamer_filter_tensorflow_lite/runTest.sh
Labels: PR/Ready2Go

#1865 Tensor-src-tizensensor: fill minor gst callbacks
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
Labels: PR/Ready2Go
