Repository nnstreamer/nnstreamer, pull requests merged in 2019-01, with the labels that each got.

#1018 DIST: apply meson/ninja to debian build
  debian/control
  debian/nnstreamer.install
  debian/rules
Labels: build

#1033 [Common] change caps format for other/tensor
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_common.h
  tests/nnstreamer_repo/runTest.sh
  tests/nnstreamer_repo_lstm/runTest.sh
  tests/nnstreamer_repo_rnn/runTest.sh
Labels: discussion

#1066 Release NNStreamer 0.1.0
  debian/changelog
  debian/control
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL

#1069 [Decoder/Boundingbox] make decoder possible to handle tensorflow ssd model
  gst/nnstreamer/tensor_decoder/tensordec-boundingbox.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
Labels: Open for Participation

#1093 [Codeowner] Add kparichay to default reviewers
  .github/CODEOWNERS
Labels: PR/Ready2Go

#1088 [Subplugin] Do not dlsym if it's already probed.
  gst/nnstreamer/nnstreamer_subplugin.c
  gst/nnstreamer/nnstreamer_subplugin.h
  gst/nnstreamer/tensor_decoder/tensordec-plugins.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
Labels: PR/Ready2Go

#1089 [Filter:*] Cut build dependency of filter-subplugin to filter
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_filter/tensor_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter_custom.c
  gst/nnstreamer/tensor_filter/tensor_filter_tensorflow.c
  gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_core.h
  gst/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.c
  gst/nnstreamer/tensor_typedef.h
Labels: PR/Ready2Go

#1097 [Conf] Bugfix: if no path is given, use current dir.
  gst/nnstreamer/nnstreamer_conf.c
Labels: PR/Ready2Go

#1103 [Conf] Bugfix of array out of bound
  gst/nnstreamer/nnstreamer_conf.c
Labels: PR/Ready2Go

#1105 [Test] runTest.sh typo
  tests/nnstreamer_decoder_image_labeling/runTest.sh
Labels: PR/Ready2Go

#1102 [DIST] Install /etc/nnstreamer.ini
  debian/nnstreamer.install
  debian/rules
  meson.build
  nnstreamer.ini
  packaging/nnstreamer.spec
Labels: PR/Ready2Go
