Repository nnstreamer/nnstreamer, pull requests merged in 2020-12, with the labels that each got.

#2506 [Tools] GstPipe String Parser
  tools/development/parser/.gitignore
  tools/development/parser/gen_grammar.py.in
  tools/development/parser/gen_lex.py.in
  tools/development/parser/grammar.y
  tools/development/parser/meson.build
  tools/development/parser/parse.l
  tools/development/parser/types.h
Labels: PR/Ready2Go

#2909 [Coverage/Fix] Exclude auto-generated files from coverage analysis
  packaging/nnstreamer.spec
Labels: discussion

#2854 [gRPC/Tests] Add some unittests for gRPC source/sink
  debian/rules
  tests/meson.build
  tests/nnstreamer_grpc/runTest.sh
  tests/nnstreamer_grpc/unittest_grpc.cc
Labels: PR/Ready2Go

#2915 [Fix/gRPC] Fix gRPC unittests to use an unused port for each test
  tests/nnstreamer_grpc/get_available_port.py
  tests/nnstreamer_grpc/runTest.sh
Labels: RELEASE CRITICAL

#2920 [Android/Build] remove unnecessary so
  api/android/build-android-lib.sh
Labels: RELEASE CRITICAL

#2919 [Debian] Fix the broken symlink
  debian/nnstreamer.links
  debian/rules
Labels: PR/Ready2Go

#2923 [Test] Fix resource and mem leak
  nnstreamer_example/custom_example_framecounter/nnscustom_framecounter.c
  tests/nnstreamer_if/unittest_if.cc
Labels: trivial

#2867 [Tools/Parser] Update gstparser's types @open sesame 12/3 12:43
  tools/development/parser/types.h
Labels: PR/Ready2Go

#2888 Release of NNStreamer 1.7.1 devel @open sesame 12/03 12:37
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2927 [Android] fix resource leak
  api/android/api/src/main/jni/nnstreamer-native-api.c
Labels: RELEASE CRITICAL

#2868 [Tools/Parser] Replace GST macros to dummy
  tools/development/parser/grammar.y
  tools/development/parser/types.c
  tools/development/parser/types.h
Labels: PR/Ready2Go

#2913 [TensorRate/Tests] Add some unittests for tensor_rate @open sesame 12/03 09:50
  gst/nnstreamer/tensor_rate/gsttensorrate.c
  tests/meson.build
  tests/nnstreamer_rate/unittest_rate.cc
Labels: PR/Ready2Go

#2870 [Tools/Parser] Parser Rule #1 and #2 updated
  tools/development/parser/grammar.y
  tools/development/parser/types.c
Labels: PR/Ready2Go

#2949 [Spec] Enable nnfw filter on x86 architecture
  packaging/nnstreamer.spec
Labels: DO NOT MERGE

#2943 [Fix/UnitTest] Add mutex to count number of callbacks @open sesame 12/14 18:32
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: PR/Ready2Go

#2884 [Tools/Parser] Parser Rule #3: chain, openchain, link, pads, morepads
  tools/development/parser/grammar.y
  tools/development/parser/types.h
Labels: PR/Ready2Go

#2922 [C-API] Define new API for tensor_if
  api/capi/include/nnstreamer.h
Labels: discussion

#2953 [gRPC/Fix] Decoupling gRPC IDL dependencies @open sesame 12/17 10:05
  debian/nnstreamer-grpc.install
  ext/nnstreamer/extra/meson.build
  ext/nnstreamer/extra/nnstreamer_grpc_common.cc
  ext/nnstreamer/extra/nnstreamer_grpc_common.h
  ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
  ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc
  ext/nnstreamer/meson.build
  packaging/nnstreamer.spec
  tests/nnstreamer_grpc/runTest.sh
Labels: PR/Ready2Go

#2957 [CAPI] Wait until the pipeline state is changed
  api/capi/src/nnstreamer-capi-pipeline.c
  gst/nnstreamer/tensor_demux/gsttensordemux.c
Labels: discussion

#2891 [Tools/Parser] Parser Rule #4: chain/openchain with URL
  tools/development/parser/grammar.y
  tools/development/parser/types.c
  tools/development/parser/types.h
Labels: PR/Ready2Go
