Repository nnstreamer/nnstreamer, pull requests merged in 2020-05, with the labels that each got.

#2341 [C-Api] new ref to get tensor name @open sesame 05/06 15:26
  api/capi/include/nnstreamer.h
  api/capi/src/nnstreamer-capi-util.c
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: Tizen 6.0 M2

#2352 [Unittest/IIO] fix mem leak of unittest_src_iio
  tests/nnstreamer_source/unittest_src_iio.cc
Labels: PR/Ready2Go

#2375 [single] Add implementation to support for hw accelerator
  api/capi/include/nnstreamer-capi-private.h
  api/capi/src/nnstreamer-capi-single.c
  api/capi/src/nnstreamer-capi-util.c
Labels: RELEASE CRITICAL

#2377 [hw/accl] Add CPU_SIMD as a backend option
  api/capi/include/nnstreamer.h
  api/capi/src/nnstreamer-capi-util.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  tests/nnstreamer_filter_tensorflow_lite/runTest.sh
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: RELEASE CRITICAL, Tizen 6.0 M2

#2305 [Meson] Provide an environment object to test() @open sesame 5/18 18:42
  meson.build
  tests/meson.build
  tests/nnstreamer_filter_edgetpu/meson.build
  tests/nnstreamer_filter_extensions_common/meson.build
  tests/nnstreamer_filter_mvncsdk2/meson.build
  tests/tizen_capi/meson.build
  tests/tizen_nnfw_runtime/meson.build
Labels: PR/Ready2Go
