Repository nnstreamer/nnstreamer, pull requests merged in 2020-07, with the labels that each got.

#2329 [Common] Allow to fetch nnstreamer version @open sesame 7/1/ 23:04
  debian/nnstreamer-dev.install
  gst/nnstreamer/include/meson.build
  gst/nnstreamer/include/nnstreamer_plugin_api.h
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/include/nnstreamer_version.h.in
  gst/nnstreamer/tensor_common.c
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
  tests/codegen/runTest.sh
  tests/common/unittest_common.cc
Labels: PR/Ready2Go

#2455 [C-Api] define new API for custom filter @open sesame 7/3 10:41
  api/capi/include/nnstreamer-capi-private.h
  api/capi/include/nnstreamer.h
  api/capi/src/nnstreamer-capi-pipeline.c
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: Tizen 6.0 M2, discussion

#2508 [C-API] Add remarks section in ml_tensors_data_create()
  api/capi/include/nnstreamer.h
Labels: PR/Ready2Go, Tizen 6.0 M2

#2533 [C-API] Add remarks section for ml_tensors_info_get_tensor_name()
  api/capi/include/nnstreamer.h
Labels: Tizen 6.0 M2

#2524 edit comment in SingleShot.java
  api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
Labels: sos-masters

#2551 [Api/Single] default no timeout when invoking model
  api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
  api/capi/include/nnstreamer-single.h
  api/capi/src/nnstreamer-capi-single.c
Labels: Tizen 6.0 M2, discussion

#2532 [Dist/Debian] Add a sub-package that provides the openvino filter @open sesame 7/21 11:30
  debian/control
  debian/nnstreamer-openvino.install
  debian/rules
  ext/nnstreamer/tensor_filter/meson.build
Labels: PR/Ready2Go

#2555 README: update example style and add more examples
  Documentation/edge-ai.md
  Documentation/products.md
  README.md
Labels: PR/Ready2Go, trivial

#2554 [Build] Support Samsung VD product build system
  api/capi/include/nnstreamer-capi-private.h
  api/capi/meson.build
  api/capi/src/nnstreamer-capi-tizen-feature-check.c
  api/capi/src/nnstreamer-capi-tizen-privilege-check.c
  meson.build
  meson_options.txt
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2571 [Protobuf] Fix protobuf util function header file
  ext/nnstreamer/extra/nnstreamer_protobuf.cc
  ext/nnstreamer/extra/nnstreamer_protobuf.h
  gst/nnstreamer/include/tensor_typedef.h
Labels: DO NOT MERGE

#2573 [Test] Remove trailing whitespace
  tests/tizen_capi/unittest_tizen_sensor.cc
Labels: sos-masters, trivial

#2576 [unittest] Bug fix for c-api unittest
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: bug

#2575 [tizensensor] Add tolerance for sensor data check @open sesame 07/28 15:30
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
Labels: PR/Ready2Go

#2583 [single] Memory leak bug fix
  api/capi/src/nnstreamer-capi-single.c
Labels: RELEASE CRITICAL

#2582 [single] Optimize invoke critical path
  api/capi/src/nnstreamer-capi-single.c
Labels: RELEASE CRITICAL

#2585 [tensor] Update GstTensorMemory coherent with ml_tensors_data_s
  api/capi/src/nnstreamer-capi-single.c
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
  ext/nnstreamer/tensor_filter/tensor_filter_openvino.hh
  ext/nnstreamer/tensor_filter/tensor_filter_python.cc
  ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
  gst/nnstreamer/include/tensor_typedef.h
  gst/nnstreamer/tensor_decoder/tensordec.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
  tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
  tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
  tests/nnstreamer_filter_openvino/unittest_openvino.cc
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: RELEASE CRITICAL
