Repository nnstreamer/nnstreamer, pull requests merged in 2020-08, with the labels that each got.

#2606 [example] Fix typo
  nnstreamer_example/custom_example_average/nnstreamer_customfilter_example_average.c
Labels: Contributhon

#2608 [C-API] Use typedef enum for feature_state
  api/capi/include/nnstreamer-capi-private.h
  api/capi/src/nnstreamer-capi-tizen-feature-check.c
  tests/tizen_capi/unittest_tizen_capi.cc
  tests/tizen_capi/unittest_tizen_sensor.cc
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: Contributhon

#2584 [filter/single] Optimize invoke path for tensor filter single
  api/capi/include/tensor_filter_single.h
  api/capi/src/tensor_filter_single.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
Labels: RELEASE CRITICAL

#2613 Revert "[Android/NNFW] change nnfw version" / Emergency
  api/android/build-android-lib.sh
Labels: PR/Ready2Go, RELEASE CRITICAL

#2569 [Single] Add unittest to measure invoke latency by single API
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  tests/tizen_capi/meson.build
  tests/tizen_capi/unittest_tizen_capi_latency.cc
Labels: RELEASE CRITICAL

#2617 [C-api] Fix typo
  api/capi/src/nnstreamer-capi-pipeline.c
Labels: Contributhon

#2592 [nnfw] Optimize nnfw invoke
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Labels: RELEASE CRITICAL

#2624 [tools] Fix typo
  tools/nnstreamer-toolkit.py
Labels: Contributhon

#2578 [tflite] Optimization for the invoke critical path @open sesame 07/28 15:00
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  tests/nnstreamer_filter_extensions_common/unittest_tizen_template.cc.in
Labels: RELEASE CRITICAL

#2597 [filter] Buf fix of setting num_tensors to 0
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
Labels: bug

#2607 [example] Use macro to copy tensor info
  nnstreamer_example/custom_example_LSTM/dummy_LSTM.c
  nnstreamer_example/custom_example_LSTM/meson.build
Labels: Contributhon

#2626 [C-api] Fix typo
  api/capi/src/nnstreamer-capi-single.c
Labels: Contributhon

#2628 [C-api] Fix typo
  api/capi/include/nnstreamer.h
Labels: Contributhon

#2656 [Android] fix data conversion error
  api/android/api/src/main/jni/nnstreamer-native-api.c
  api/android/api/src/main/jni/nnstreamer-native-singleshot.c
  api/android/api/src/main/jni/nnstreamer-native.h
Labels: bug

#2649 [single] Bug fix for setting accelerator @open sesame 8/15 18:50
  api/capi/src/nnstreamer-capi-single.c
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: RELEASE CRITICAL, bug

#2655 [Ext/Decoder] Support face detection models for OpenVino
  ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
Labels: PR/Ready2Go
