Repository nnstreamer/nnstreamer, pull requests merged in 2020-04, with the labels that each got.

#2237 [CODEOWNERS] Update reviewer lists
  .github/CODEOWNERS
Labels: trivial

#2131 [tensor_filter] Support tensor filter framework v1 callbacks for the pipeline @open sesame 3/27 17:13
  gst/nnstreamer/tensor_filter/tensor_filter.c
Labels: PR/Ready2Go

#2225 [Dist/Tizen] Correct LD_LIBRARY_PATH for NCSDK2/Edge-TPU test cases
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2241 [Tests/CAPI] Fix test case to stable in arm arch
  tests/nnstreamer_decoder_image_segment/runTest.sh
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: DO NOT MERGE

#2213 [Android/Build] option to get sdk path @open sesame 03/27 16:25
  api/android/build-android-lib.sh
Labels: PR/Ready2Go

#2249 [Example/custom/opencv] Use enumeration in imgproc.hpp
  nnstreamer_example/custom_example_opencv/nnstreamer_customfilter_opencv_scaler.cc
Labels: PR/Ready2Go

#2252 Start development of 1.5.2 as 1.6.0-RC3
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2263 [Tizen 5.5 / GLIBC 2.24] Workaround for GLIBC bug
  gst/nnstreamer/nnstreamer_subplugin.c
Labels: RELEASE CRITICAL

#2132 [tensor_filter] Support tensor filter framework v1 callbacks for single API
  api/capi/src/tensor_filter_single.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.h
Labels: PR/Ready2Go

#2261 [Tests/CAPI] Use constexpr instead of define and ifdef for tflite @open sesame 04/13 15:19:47
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: PR/Ready2Go

#2283 [Bug] Do not call essential ops in assert(). @open sesame 4/18 12:34
  ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
  ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
  ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
  ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
  ext/nnstreamer/tensor_decoder/tensordec-pose.c
  gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
  gst/nnstreamer/tensor_converter/tensor_converter.c
  gst/nnstreamer/tensor_decoder/tensordec.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_merge/gsttensormerge.c
  gst/nnstreamer/tensor_mux/gsttensormux.c
  gst/nnstreamer/tensor_repo/tensor_reposrc.c
  gst/nnstreamer/tensor_source/tensor_src_iio.c
  gst/nnstreamer/tensor_split/gsttensorsplit.c
  gst/nnstreamer/tensor_transform/tensor_transform.c
Labels: RELEASE CRITICAL

#2218 [UPDATING THE RULE!] Comply with LF/AI Community Charter
  CONTRIBUTING.md
  Documentation/contributing.md
  MAINTAINERS.md
Labels: Non-Technial

#2311 [Test/NNFW] ignore timeout in singleshot
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: RELEASE CRITICAL

#2310 [TEST] Fix tizen sensor unit test
  tests/tizen_capi/meson.build
  tests/tizen_capi/unittest_tizen_sensor.cc
Labels: RELEASE CRITICAL

#2300 [Dist/Tizen] Use the base option, b_coverage, to track coverage
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2291 Error return instead of assert for external errors.
  ext/nnstreamer/android_source/gstamcsrc_looper.cc
  ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
  ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
  ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
  ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
  ext/nnstreamer/tensor_decoder/tensordec-pose.c
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  gst/nnstreamer/nnstreamer_conf.c
  gst/nnstreamer/nnstreamer_subplugin.c
  gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_common_pipeline.c
  gst/nnstreamer/tensor_converter/tensor_converter.c
  gst/nnstreamer/tensor_decoder/tensordec.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  gst/nnstreamer/tensor_filter/tensor_filter_custom.c
  gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
  gst/nnstreamer/tensor_merge/gsttensormerge.c
  gst/nnstreamer/tensor_mux/gsttensormux.c
  gst/nnstreamer/tensor_repo/tensor_repo.c
  gst/nnstreamer/tensor_repo/tensor_reposrc.c
  gst/nnstreamer/tensor_split/gsttensorsplit.c
  gst/nnstreamer/tensor_transform/tensor_transform.c
Labels: PR/Ready2Go
