Repository nnstreamer/nnstreamer, pull requests merged in 2020-06, with the labels that each got.

#2399 [Unittest] Fix a potential bug of unit testcase
  tests/nnstreamer_plugins/unittest_plugins.cc
Labels: PR/Ready2Go

#2398 [Android] cache method id @open sesame 5/28 20:00
  api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
  api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java
  api/android/api/src/main/jni/nnstreamer-native-api.c
  api/android/api/src/main/jni/nnstreamer-native-customfilter.c
  api/android/api/src/main/jni/nnstreamer-native-pipeline.c
  api/android/api/src/main/jni/nnstreamer-native-singleshot.c
  api/android/api/src/main/jni/nnstreamer-native.h
Labels: PR/Ready2Go

#2208 [Decoder/protobuf] Add protobuf tensor_decoder sub-plugin
  ext/nnstreamer/include/nnstreamer.proto
  ext/nnstreamer/meson.build
  ext/nnstreamer/tensor_decoder/meson.build
  ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc
  gst/nnstreamer/include/tensor_typedef.h
  meson.build
  meson_options.txt
Labels: PR/Ready2Go

#2422 [Filter/Prop] Add performance properties (lat/fps) for tensor filter
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.h
Labels: PR/Ready2Go

#2413 [Decoder] Extend tensordec-imagesegment to support snpe-deeplab/depth
  ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
Labels: PR/Ready2Go

#2427 [Filter/TFLite] remove ineffective codes
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
Labels: PR/Ready2Go

#2436 Tizen/spec: disable mvncsdk/edgeTPU for DA build
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL

#2415 [Decoder/Neon] Support neon accl for SNPE deeplab/depth decoder @open sesame 6/5 13:19
  ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
Labels: PR/Ready2Go

#2454 [Debian/control] Add flatbuf-dev build dependent package @open sesame 6/11 12:49
  debian/control
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2382 [Flatbuf] Add tensor converter subplugin for flatbuffer
  debian/rules
  ext/nnstreamer/include/nnstreamer.fbs
  ext/nnstreamer/meson.build
  ext/nnstreamer/tensor_converter/meson.build
  ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
  meson.build
  meson_options.txt
  packaging/nnstreamer.spec
  packaging/run_unittests_binaries.sh
Labels: PR/Ready2Go

#2129 [Decoder] Add tensor decoder subplugin flatbuffers @open sesame 6/19 16:19
  ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
  ext/nnstreamer/tensor_decoder/meson.build
  ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
Labels: PR/Ready2Go

#2494 [TEST] Fix Tensor converter test
  tests/nnstreamer_converter/runTest.sh
Labels: trivial
