Repository nnstreamer/nnstreamer, pull requests merged in 2020-10, with the labels that each got.

#2762 [Meson] Merge install-example into install-test @open sesame 9/24 16:02
  debian/rules
  meson.build
  meson_options.txt
  nnstreamer_example/custom_example_LSTM/meson.build
  nnstreamer_example/custom_example_RNN/meson.build
  nnstreamer_example/custom_example_average/meson.build
  nnstreamer_example/custom_example_opencv/meson.build
  nnstreamer_example/custom_example_passthrough/meson.build
  nnstreamer_example/custom_example_scaler/meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2760 [Build/TF-Lite] Check tf-lite version and don't use contrib path @open sesame 9/24 16:03
  ext/nnstreamer/tensor_filter/meson.build
  ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
Labels: PR/Ready2Go

#2735 [Custom/TensorRT] Implement example custom filter for TensorRT @open sesame 9/24 16:03
  nnstreamer_example/custom_example_tensorrt/meson.build
  nnstreamer_example/custom_example_tensorrt/nnstreamer_customfilter_example_tensorrt_reshape.cc
  nnstreamer_example/meson.build
  tests/nnstreamer_filter_custom/runTest.sh
Labels: PR/Ready2Go

#2745 [TensorIF] Add README.md for tensor_if element @open sesame 9/24 15:25
  gst/nnstreamer/tensor_if/README.md
Labels: discussion

#2798 [Meson] Fix the buildbreak of custom_example_tensorrt example
  nnstreamer_example/meson.build
Labels: PR/Ready2Go

#2773 [TensorIF] Add basic action option
  gst/nnstreamer/tensor_if/gsttensorif.c
Labels: PR/Ready2Go

#2769 [TensorRate] Implement the prototype codes for tensor_rate element @open sesame 10/12 12:19
  gst/nnstreamer/meson.build
  gst/nnstreamer/registerer/nnstreamer.c
  gst/nnstreamer/tensor_rate/gsttensorrate.c
  gst/nnstreamer/tensor_rate/gsttensorrate.h
  gst/nnstreamer/tensor_rate/meson.build
  jni/nnstreamer.mk
Labels: PR/Ready2Go

#2788 [Filter/NNFW] dummy invoke after set-info called
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Labels: RELEASE CRITICAL

#2804 [ONE/Android] prepare ONE-1.10.0 release
  api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
  api/android/build-android-lib.sh
Labels: PR/Ready2Go

#2808 [Tensor Transform] Fix unsupported orc type cast
  gst/nnstreamer/tensor_transform/tensor_transform.c
Labels: PR/Ready2Go

#2776 [TensorIF] Supports other/tensor(s) in output format
  gst/nnstreamer/tensor_if/gsttensorif.c
  gst/nnstreamer/tensor_if/gsttensorif.h
Labels: PR/Ready2Go

#2824 [Fix/Debian] Add missing installation files (nnstreamer-check/capi)
  debian/nnstreamer-dev.install
  debian/nnstreamer.install
  debian/rules
Labels: PR/Ready2Go

#2815 [Build/ExtPlugin] Add registerer for ext plugins (tizensensor, gRPC, ...)
  ext/nnstreamer/meson.build
  ext/nnstreamer/registerer/tizensensor.c
  ext/nnstreamer/tensor_source/meson.build
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.h
  meson.build
  packaging/nnstreamer.spec
  tests/tizen_capi/meson.build
Labels: PR/Ready2Go

#2778 [TensorIF] Supports tensor average option for compared value
  gst/nnstreamer/tensor_if/gsttensorif.c
Labels: PR/Ready2Go

#2818 [C-Api] prepare new APIs
  api/android/api/src/main/jni/nnstreamer-native-singleshot.c
  api/capi/include/nnstreamer-capi-private.h
  api/capi/include/nnstreamer-single.h
  api/capi/src/nnstreamer-capi-single.c
  tests/tizen_capi/unittest_tizen_capi.cc
  tests/tizen_capi/unittest_tizen_capi_latency.cc
Labels: discussion

#2837 [Dist/Debian] Move libcapi-nnstreamer.a and .so to the development package
  debian/nnstreamer-dev.install
  debian/nnstreamer.install
Labels: RELEASE CRITICAL, bug

#2845 [Repo] Fix the assertion error when executing `gst-inspect-1.0 command
  gst/nnstreamer/tensor_repo/tensor_reposrc.c
Labels: PR/Ready2Go
