Repository nnstreamer/nnstreamer, pull requests merged in 2020-02, with the labels that each got.

#2082 [build/tizen] Identify build failure correctly
  packaging/run_unittests_binaries.sh
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: RELEASE CRITICAL

#2049 Fix: subplugin infra: dlclose & free handles at exit
  gst/nnstreamer/nnstreamer_subplugin.c
Labels: PR/Ready2Go

#2047 Filter/C++: Fix potential memory leak.
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.hh
Labels: PR/Ready2Go

#2072 [subplugins] Refactor subplugin interface
  ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
  ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
  ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
  ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
  ext/nnstreamer/tensor_filter/tensor_filter_python.cc
  ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  gst/nnstreamer/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_filter/tensor_filter_custom.c
  gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
Labels: discussion

#2096 [Wait 4 #2072 #2039] Release of 1.4.0 / Start of 1.5.0
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#2088 [Api] prepare release process
  api/capi/include/nnstreamer-single.h
  api/capi/include/nnstreamer.h
Labels: Tizen 6.0 M1

#2106 Aggregator/Doc: add dis-aggregator notes. @open sesame 02/14 15:10
  gst/nnstreamer/tensor_aggregator/README.md
Labels: trivial

#2119 [TFLite] add the datatype with meson option
  meson.build
  meson_options.txt
Labels: PR/Ready2Go

#2109 [Wait for #2119] Support models with signed 8-bit integer I/O
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
Labels: PR/Ready2Go

#2120 [TFLite] check supporting datatype
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
Labels: PR/Ready2Go
