Repository nnstreamer/nnstreamer, pull requests merged in 2020-03, with the labels that each got.

#2126 [Coverity] fix coverity issue
  tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
  tests/nnstreamer_sink/unittest_sink.cc
  tests/tizen_capi/unittest_tizen_capi.cc
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: Tizen 6.0 M1

#2138 [Test] filesink buffer mode
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: PR/Ready2Go

#2140 Test/License: Add WordNet License File.
  tests/test_models/labels/LICENSE.WordNet3
Labels: RELEASE CRITICAL, Tizen 6.0 M1

#2143 [Api] hw enum for sr-npu
  api/capi/include/nnstreamer.h
  api/capi/src/nnstreamer-capi-util.c
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: Tizen 6.0 M1

#2167 [Filter/Sub] preserved name
  api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
  gst/nnstreamer/nnstreamer_subplugin.c
  tests/nnstreamer_sink/unittest_sink.cc
Labels: discussion

#2175 Start development of 1.5.1 as 1.6.0-RC2
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go, trivial

#2039 New Filter Subplugin Interface Draft: C++ support
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.hh
  gst/nnstreamer/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/meson.build
  gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
  gst/nnstreamer/tensor_filter/tensor_filter_support_cc.hh
  meson_options.txt
Labels: PR/Ready2Go

#2174 [Tests/Filter/Reload] Check existence of TFLite filters before start
  tests/nnstreamer_filter_reload/runTest.sh
Labels: PR/Ready2Go

#2196 [LF/AI] Remove Samsung Proprietary/Confidential notice
  Documentation/doxygen-documentation.md
Labels: PR/Ready2Go, trivial

#2195 Fix: Tizen 6.0 FHUB QB is too slow. @open sesame 3/23 11:43
  tests/tizen_capi/unittest_tizen_sensor.cc
Labels: RELEASE CRITICAL, Tizen 6.0 M1

#2189 [Coverity/1133962] Prevent NULL dereference
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: RELEASE CRITICAL

#2193 [Infra] Move exported headers to .../include/
  api/android/build-android-lib.sh
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
  gst/nnstreamer/README.md
  gst/nnstreamer/include/README.md
  gst/nnstreamer/include/meson.build
  gst/nnstreamer/include/nnstreamer_cppplugin_api_filter.hh
  gst/nnstreamer/include/nnstreamer_plugin_api.h
  gst/nnstreamer/include/nnstreamer_plugin_api_converter.h
  gst/nnstreamer/include/nnstreamer_plugin_api_decoder.h
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/include/tensor_filter_custom.h
  gst/nnstreamer/include/tensor_filter_custom_easy.h
  gst/nnstreamer/include/tensor_typedef.h
  gst/nnstreamer/meson.build
  gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
  jni/nnstreamer.mk
  tests/codegen/runTest.sh
Labels: PR/Ready2Go

#2184 [C-API] add testcases for a function: `ml_single_invoke_dynamic()`
  tests/tizen_capi/unittest_tizen_capi.cc
Labels: RELEASE CRITICAL

#2207 [Android/Build] Add comments on TF-Lite versions and types.
  api/android/api/src/main/jni/Android.mk
Labels: trivial

#2224 [Dist/Tizen] Add workaround for mvnc filter test failure on Tizen
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL
