Repository nnstreamer/nnstreamer, pull requests merged in 2020-09, with the labels that each got.

#2682 [Android] deallocate direct buffer
  api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
  api/android/api/src/main/jni/nnstreamer-native-api.c
  api/android/api/src/main/jni/nnstreamer-native-singleshot.c
  api/android/api/src/main/jni/nnstreamer-native.h
Labels: RELEASE CRITICAL, bug

#2685 [Bug/TensorSplit] Fix the offset calculation bug
  gst/nnstreamer/tensor_split/gsttensorsplit.c
Labels: bug

#2696 [Android/NNFW] update version
  api/android/build-android-lib.sh
Labels: RELEASE CRITICAL

#2688 onert(nnfw) uses 'cpu;bcq' as default backend
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Labels: RELEASE CRITICAL

#2697 [SVACE] fix svace issue
  gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
Labels: RELEASE CRITICAL

#2687 [Android/NNFW] parse option
  api/android/api/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Labels: RELEASE CRITICAL

#2705 [Android] reduce method call
  api/android/api/src/main/java/org/nnsuite/nnstreamer/TensorsData.java
  api/android/api/src/main/jni/nnstreamer-native-api.c
  api/android/api/src/main/jni/nnstreamer-native.h
Labels: RELEASE CRITICAL

#2706 [TF-lite] remove nnfw-delegate feature
  ext/nnstreamer/tensor_filter/meson.build
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  meson.build
  meson_options.txt
Labels: PR/Ready2Go, for-next

#2699 [hw/accl] move h/w dependent code out of filter + Bug Fix
  gst/nnstreamer/hw_accel.c
  gst/nnstreamer/hw_accel.h
  gst/nnstreamer/meson.build
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  jni/nnstreamer.mk
Labels: for-next

#2708 [Coverity/Common] Fix CWE-476 in tensor_common
  gst/nnstreamer/tensor_common.c
Labels: RELEASE CRITICAL

#2709 [Coverity/Repo] Fix CWE-366 in tensor_repo
  gst/nnstreamer/tensor_repo/tensor_repo.c
Labels: RELEASE CRITICAL

#2710 [Coverity] Fix CWE-466 (Lock) in tizensensor_get_property
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
Labels: RELEASE CRITICAL

#2713 [ Tensor Filter ] Inference Element for NNTrainer
  ext/nnstreamer/tensor_filter/meson.build
  ext/nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
  meson.build
  meson_options.txt
  packaging/nnstreamer.spec
  tests/nnstreamer_filter_nntrainer/checkLabel.py
  tests/nnstreamer_filter_nntrainer/runTest.sh
  tests/test_models/data/0.png
  tests/test_models/data/2.png
  tests/test_models/models/mnist.ini
  tests/test_models/models/model.bin
Labels: DO NOT MERGE, RELEASE CRITICAL, Tizen 6.0 M2, discussion

#2715 [tools/debugging] Add how to trace a specific NNStreamer element
  tools/debugging/README.md
Labels: Contributhon, for-next

#2714 [ext/tensor_decoder] Configure framerate caps for all tensor_decoders
  ext/nnstreamer/tensor_decoder/meson.build
  ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
  ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
  ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
  ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
  ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
  ext/nnstreamer/tensor_decoder/tensordec-pose.c
  ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc
  ext/nnstreamer/tensor_decoder/tensordecutil.c
  ext/nnstreamer/tensor_decoder/tensordecutil.h
Labels: Contributhon, for-next

#2707 [Coverity] Fix unreachable codes
  api/capi/src/nnstreamer-capi-util.c
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Labels: RELEASE CRITICAL, Tizen 6.0 M2

#2739 [Meson] bugfixes: Add missing dependency in flatbuffer-support declaration
  meson.build
Labels: RELEASE CRITICAL, bug

#2744 [Android/Test] test for dynamic dim
  api/android/api/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
Labels: for-next

#2743 [Filter/NNFW] enable set-dim function
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
Labels: for-next

#2738 [Build/TensorRT] Add TensorRT dependency
  meson.build
  meson_options.txt
Labels: for-next

#2674 [Filter,V2] Added a framework to support TF2-Lite (2.3.0) @open sesame 09/04 12:07
  ext/nnstreamer/tensor_filter/meson.build
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  meson.build
  meson_options.txt
  packaging/nnstreamer.spec
  tests/meson.build
  tests/nnstreamer_filter_tensorflow2_lite/checkLabel.py
  tests/nnstreamer_filter_tensorflow2_lite/runTest.sh
Labels: Open for Participation, for-next

#2752 [Meson] Enable fbs-support only if versions of flatc and libs are matched @open sesame 09/22 11:55
  ext/nnstreamer/meson.build
  meson.build
Labels: PR/Ready2Go

#2747 [Android] new function to create data object
  api/android/api/src/main/jni/nnstreamer-native-api.c
  api/android/api/src/main/jni/nnstreamer-native.h
Labels: RELEASE CRITICAL

#2750 [C-Api/Single] prepare no-alloc invoke
  api/capi/src/nnstreamer-capi-single.c
Labels: RELEASE CRITICAL

#2767 [Meson] change license arg
  api/capi/meson.build
  meson.build
  tools/development/confchk/meson.build
  tools/development/nnstreamerCodeGenCustomFilter.py
Labels: lts

#2775 [docs] Update getting-started with minimal requirement @open sesame 09/28 19:18
  Documentation/getting-started-meson-build.md
Labels: trivial
