Repository nnstreamer/nnstreamer, pull requests merged in 2021-08, with the labels that each got.

#3434 [Doc] Add serialized buffer description
  gst/nnstreamer/tensor_converter/README.md
  gst/nnstreamer/tensor_decoder/README.md
Labels: trivial

#3418 [Config/Format] tensor format in config
  gst/nnstreamer/include/nnstreamer_plugin_api.h
  gst/nnstreamer/include/tensor_typedef.h
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_common_pipeline.c
  gst/nnstreamer/tensor_crop/tensor_crop.c
  gst/nnstreamer/tensor_demux/gsttensordemux.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  gst/nnstreamer/tensor_mux/gsttensormux.c
  gst/nnstreamer/tensor_transform/tensor_transform.c
  tests/common/unittest_common.cc
  tests/nnstreamer_plugins/unittest_plugins.cc
  tests/nnstreamer_sink/unittest_sink.cc
Labels: PR/Ready2Go

#3436 [Filter] Rename srnpu to trixengine
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
Labels: DO NOT MERGE

#3463 [Filter/Sub] add event handler for filter-fw v0
  ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
  ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
  ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
  ext/nnstreamer/tensor_filter/tensor_filter_python3.cc
  ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/nnstreamer_internal.h
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.h
  gst/nnstreamer/tensor_filter/tensor_filter_custom.c
Labels: discussion, Tizen 6.5 M2
