Repository nnstreamer/nnstreamer, pull requests merged in 2021-07, with the labels that each got.

#3387 [Doc] fix param annotation
  gst/nnstreamer/include/nnstreamer_plugin_api.h
  gst/nnstreamer/tensor_common.c
Labels: trivial

#3383 [Doc] Fix title to comply hotdoc rule
  Documentation/profiling-android-pipeline.md
Labels: trivial

#3398 [Doc] Fix android documentation
  Documentation/getting-started-android.md
Labels: trivial

#3403 [Tests/GRPC] Skip GRPC tests on the qemu/arm environment either @open sesame 07/17 18:00
  packaging/nnstreamer.spec
  tests/nnstreamer_grpc/runTest.sh
Labels: PR/Ready2Go

#3411 Decoder: Bounding boxes: option3 comments update / After #3408
  ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
Labels: PR/Ready2Go

#3419 [Build/Deb] dependency to NNFW @open sesame 06/21 13:48
  debian/control
  debian/control.ubuntu.ppa
  debian/nnstreamer-nnfw.install
Labels: PR/Ready2Go

#3350 [SparseTensor] Define SparseTensor and API @open sesame 07/06 09:45
  gst/nnstreamer/include/tensor_typedef.h
  gst/nnstreamer/tensor_sparse/tensor_sparse_util.h
Labels: discussion

#3389 [Common] remove tensor-config struct
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
  gst/nnstreamer/include/nnstreamer_plugin_api.h
  gst/nnstreamer/include/tensor_typedef.h
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_source/tensor_src_iio.c
  gst/nnstreamer/tensor_transform/tensor_transform.c
  tests/common/unittest_common.cc
  tests/nnstreamer_converter/unittest_converter.cc
  tests/nnstreamer_plugins/unittest_plugins.cc
  tests/nnstreamer_source/unittest_src_iio.cc
Labels: PR/Ready2Go
