Repository nnstreamer/nnstreamer, pull requests merged in 2021-06, with the labels that each got.

#3273 [Meta] define tensor meta
  gst/nnstreamer/include/tensor_typedef.h
Labels: discussion

#3296 [Flex/Common] util functions to handle pad caps
  gst/nnstreamer/include/nnstreamer_plugin_api.h
  gst/nnstreamer/nnstreamer_internal.h
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_common.h
  gst/nnstreamer/tensor_converter/tensor_converter.c
  gst/nnstreamer/tensor_demux/gsttensordemux.c
  gst/nnstreamer/tensor_if/gsttensorif.c
  gst/nnstreamer/tensor_mux/gsttensormux.c
Labels: PR/Ready2Go

#3323 [TEST] Change timeout of the tensor_if test
  tests/nnstreamer_if/unittest_if.cc
Labels: trivial

#3308 [TensorFilter] add a property shared-tensor-filter-key
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
Labels: PR/Ready2Go

#3334 [Transform] set write flag
  gst/nnstreamer/tensor_transform/tensor_transform.c
Labels: PR/Ready2Go

#3335 [Common/MemFlag] remove read-only flag
  ext/nnstreamer/extra/nnstreamer_grpc_flatbuf.cc
  ext/nnstreamer/extra/nnstreamer_grpc_protobuf.cc
  ext/nnstreamer/extra/nnstreamer_protobuf.cc
  ext/nnstreamer/tensor_converter/tensor_converter_python3.cc
  tests/nnstreamer_converter/unittest_converter.cc
  tests/nnstreamer_plugins/unittest_plugins.cc
Labels: PR/Ready2Go

#3338 [TEST] Fix python converter test fail on arm arch
  tests/nnstreamer_converter/unittest_converter.cc
  tests/test_models/models/custom_converter_test.py
Labels: trivial

#3349 [Spec] Fix DA build error
  packaging/nnstreamer.spec
Labels: bug

#3371 [TensorFilter] Add SLSI NPU option as HW accelerator
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
Labels: PR/Ready2Go
