Repository nnstreamer/nnstreamer, pull requests merged in 2021-05, with the labels that each got.

#3238 [If] invalid map info
  gst/nnstreamer/tensor_if/gsttensorif.c
Labels: PR/Ready2Go

#3240 [TEST] Separate positive and negative tests @open sesame 05/04 13:25
  tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
Labels: PR/Ready2Go, trivial

#3217 [Test/TVM] Add unittest for TVM subplugin
  tests/meson.build
  tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc
  tests/test_models/models/tvm_add_one.so_
Labels: PR/Ready2Go

#3256 [Tests/Converter] Fix -Werror=sign-compare error
  tests/nnstreamer_converter/unittest_converter.cc
Labels: trivial

#3257 [Transform] change val name in macro
  gst/nnstreamer/tensor_transform/tensor_transform.c
Labels: PR/Ready2Go

#3234 [Gst/MQTT] Fix memory leaks and add a new property to enable debugging outputs
  gst/mqtt/mqttsink.c
  gst/mqtt/mqttsink.h
  gst/mqtt/mqttsrc.c
  gst/mqtt/mqttsrc.h
Labels: PR/Ready2Go, trivial

#3235 [Gst/MQTT/Src] Handle the messages with relatively long jitters or delays @open sesame 05/12 10:20
  gst/mqtt/mqttsrc.c
  gst/mqtt/mqttsrc.h
Labels: PR/Ready2Go

#3269 [Fix/Filter] Fix tensors info initialization
  ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
  ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
Labels: bug

#3262 [Tools/Parser] Find element name in the pipeline @open sesame 05/13 13:33
  tools/development/parser/types.c
  tools/development/parser/types.h
Labels: PR/Ready2Go

#3263 [Tools/Parser] Add nnstreamer-parser to util package @open sesame 05/13 17:13
  debian/control
  debian/nnstreamer-util.install
  debian/nnstreamer-util.links
  meson_options.txt
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#3270 [Tools/Parser] Convert gst pipeline to pbtxt (w/ mediapipe demo site)
  tools/development/parser/convert.c
  tools/development/parser/convert.h
  tools/development/parser/grammar.y
  tools/development/parser/meson.build
  tools/development/parser/toplevel.c
  tools/development/parser/types.c
  tools/development/parser/types.h
Labels: PR/Ready2Go

#3293 [Gst/MQTT] Revise README.md
  gst/mqtt/README.md
Labels: trivial

#3299 [Coverage/Tools] Ignore coverage report of source codes in tools
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#3279 [Gst/MQTT/Src] Keep subscribing to the topic only in the PLAYING state
  gst/mqtt/mqttsrc.c
Labels: PR/Ready2Go

#3290 [Converter/CodeClean] unnecessary memory map
  gst/nnstreamer/tensor_converter/tensor_converter.c
Labels: PR/Ready2Go

#3309 [CodeClean/Tool] remove gv in am report
  tools/development/parser/convert.c
Labels: PR/Ready2Go, trivial
