Repository nnstreamer/nnstreamer, pull requests merged in 2021-03, with the labels that each got.

#3091 [Meson] Revise build dependency checking mechanism for MvNCSDK2 @open sesame 03/23 12:48
  meson.build
Labels: PR/Ready2Go

#3107 [Build] fix install path
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#3108 Revert "[Debian] Temporally disable caffe2/tensorflow"
  debian/nnstreamer-caffe2.install
  debian/nnstreamer-tensorflow.install
  debian/rules
Labels: PR/Ready2Go

#3110 [Python] Change the logic to find the python library name
  ext/nnstreamer/tensor_filter/tensor_filter_python3.cc
Labels: PR/Ready2Go

#3116 [Doc] Change hotdoc generation script
  Documentation/hotdoc/doc-index.md
  Documentation/hotdoc/gen-hotdoc.sh
  Documentation/hotdoc/sitemap.txt
  Documentation/hotdoc/theme/extra/templates/navbar_links.html
  index.md
Labels: PR/Ready2Go

#3140 [Fix] Add missing file section in rpm build
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL

#3139 [Spec] Fix the buildbreak issue for VD
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL

#3101 [Filter/Lua] Design of LUA script rules for nnstreamer.
  ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
Labels: PR/Ready2Go

#3160 CODEOWNERS: Add members
  .github/CODEOWNERS
Labels: Non-Technical, trivial

#3158 [Doc] Modify tensor_if README.md
  gst/nnstreamer/tensor_if/README.md
Labels: trivial

#3155 [CONVERTER] Change custom mode name
  ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
  gst/nnstreamer/include/tensor_converter_custom.h
  gst/nnstreamer/tensor_converter/tensor_converter.c
  gst/nnstreamer/tensor_converter/tensor_converter.h
  tests/nnstreamer_converter/unittest_converter.cc
Labels: PR/Ready2Go

#3147 [RPM] Add virtual conf package @open sesame 03/23 14:18
  packaging/nnstreamer.spec
Labels: PR/Ready2Go, RELEASE CRITICAL

#3156 [Spec] Remove archiving script
  packaging/generate-tarball.sh
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#3168 [Doc] Fix typo in md files
  CONTRIBUTING.md
  Documentation/coding-convention.md
  Documentation/component-description.md
  Documentation/data-type-and-flow-control.md
  Documentation/getting-started-android.md
  Documentation/getting-started-ubuntu-ppa.md
  Documentation/writing-subplugin-tensor-filter.md
Labels: trivial

#3171 [TizenSensor] init sensor type
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
Labels: PR/Ready2Go
