Repository nnstreamer/nnstreamer, pull requests merged in 2021-02, with the labels that each got.

#2908 [Tools/Parser] Other All Remaining Rules
  tools/development/parser/grammar.y
  tools/development/parser/types.c
  tools/development/parser/types.h
Labels: PR/Ready2Go

#3028 [C-API] Fix C-API header comments
  api/capi/include/nnstreamer-single.h
  api/capi/include/nnstreamer.h
Labels: PR/Ready2Go

#3041 [Doc] Add nnstreamer logo to github.io @open sesame 2/02 10:34
  Documentation/hotdoc/theme/extra/images/nnstreamer_logo.png
  Documentation/hotdoc/theme/extra/templates/brand-logo.html
  Documentation/hotdoc/theme/extra/templates/extra_head.html
Labels: trivial

#3025 [Doc] Add NNStreamer wiki to github.io
  Documentation/data-type-and-flow-control.md
  Documentation/getting-started-android.md
  Documentation/gst-launch-script-example.md
  Documentation/hotdoc/sitemap.txt
  Documentation/how-to-run-examples.md
  Documentation/media/exam_cam_mix.png
  Documentation/media/exam_filter_keyboard.png
  Documentation/media/exam_filter_mouse.png
  Documentation/media/exam_object_detection_result_tf.png
  Documentation/media/exam_object_detection_result_tflite.png
  Documentation/rank-counting-with-other-tensor.md
  Documentation/synchronization-policies-at-mux-merge.md
Labels: discussion

#3062 [Filter] Fix memory leak
  gst/nnstreamer/include/nnstreamer_plugin_api_filter.h
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
Labels: RELEASE CRITICAL

#3068 [CAPI] Change comment to comply convention @open sesame 02/15 15:32
  api/capi/include/nnstreamer.h
Labels: trivial

#3075 [Build/Dev] internal header in cpp
  gst/nnstreamer/nnstreamer_internal.h
Labels: PR/Ready2Go

#3070 [Build] disable c-api
  debian/control
  debian/nnstreamer-api-common-dev.install
  debian/nnstreamer-api-dev.install
  debian/nnstreamer-api.install
  debian/rules
  meson.build
  meson_options.txt
  packaging/capi-nnstreamer.manifest
  packaging/nnstreamer.spec
  tests/meson.build
  tests/tizen_capi/meson.build
  tests/tizen_sensor/dummy_sensor.c
  tests/tizen_sensor/dummy_sensor.h
  tests/tizen_sensor/meson.build
  tests/tizen_sensor/sensor.h
  tests/tizen_sensor/unittest_tizen_capi.cc
  tests/tizen_sensor/unittest_tizen_capi_latency.cc
  tests/tizen_sensor/unittest_tizen_sensor.cc
Labels: PR/Ready2Go
