Repository nnstreamer/nnstreamer, pull requests merged in 2021-04, with the labels that each got.

#3177 [Filter/EdgeTPU] tf-lite ver for EdgeTPU
  ext/nnstreamer/tensor_filter/meson.build
Labels: discussion

#3181 Change gboolean comparison
  ext/nnstreamer/extra/nnstreamer_protobuf.cc
  ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
  ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
  ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c
  ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
  ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
  ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
  ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
  ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
  ext/nnstreamer/tensor_decoder/tensordec-pose.c
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
  gst/nnstreamer/nnstreamer_conf.c
  gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_common_pipeline.c
  gst/nnstreamer/tensor_converter/tensor_converter.c
  gst/nnstreamer/tensor_decoder/tensordec.c
  gst/nnstreamer/tensor_filter/tensor_filter.c
  gst/nnstreamer/tensor_filter/tensor_filter_common.c
  gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
  gst/nnstreamer/tensor_filter/tensor_filter_single.c
  gst/nnstreamer/tensor_if/gsttensorif.c
  gst/nnstreamer/tensor_merge/gsttensormerge.c
  gst/nnstreamer/tensor_repo/tensor_reposrc.c
  gst/nnstreamer/tensor_source/tensor_src_iio.c
  gst/nnstreamer/tensor_split/gsttensorsplit.c
  gst/nnstreamer/tensor_transform/tensor_transform.c
  tests/common/unittest_common.cc
  tests/nnstreamer_converter/unittest_converter.cc
  tests/nnstreamer_decoder/unittest_decoder.cc
  tests/nnstreamer_filter_armnn/unittest_filter_armnn.cc
  tests/tizen_nnfw_runtime/unittest_tizen_nnfw_runtime_raw.cc
Labels: trivial

#3183 [Mux/Merge] change property name
  Documentation/synchronization-policies-at-mux-merge.md
  gst/nnstreamer/tensor_common.h
  gst/nnstreamer/tensor_common_pipeline.c
  gst/nnstreamer/tensor_merge/gsttensormerge.c
  gst/nnstreamer/tensor_mux/gsttensormux.c
  tests/nnstreamer_flatbuf/runTest.sh
  tests/nnstreamer_flexbuf/runTest.sh
  tests/nnstreamer_merge/runTest.sh
  tests/nnstreamer_mux/runTest.sh
  tests/nnstreamer_protobuf/runTest.sh
  tests/nnstreamer_repo_lstm/runTest.sh
  tests/nnstreamer_repo_rnn/runTest.sh
  tests/nnstreamer_sink/unittest_sink.cc
Labels: PR/Ready2Go

#3179 [aggregator/converter] Fix when GST_EVENT_FLUSH_*
  gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
  gst/nnstreamer/tensor_converter/tensor_converter.c
Labels: PR/Ready2Go

#3185 [TCM] Modify tca config files @open sesame 04/07 10:18
  .ahub/tcchecker-tca/config_android.yaml
  .ahub/tcchecker-tca/config_nnstreamer.yaml
Labels: PR/Ready2Go

#3199 [Doc] Change menu tree name of contributing doc.
  Documentation/contributing.md
  Documentation/hotdoc/sitemap.txt
Labels: trivial

#3205 [Docs] Change nnstreamer CI server link
  Documentation/API-reference.md
  Documentation/component-description.md
  Documentation/writing-subplugin-tensor-filter.md
  README.md
  jni/README.md
Labels: trivial

#3204 [indent] Change indent style
  ext/nnstreamer/tensor_converter/tensor_converter_flatbuf.cc
  ext/nnstreamer/tensor_converter/tensor_converter_flexbuf.cc
  ext/nnstreamer/tensor_converter/tensor_converter_protobuf.cc
  ext/nnstreamer/tensor_decoder/tensordec-directvideo.c
  ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
  ext/nnstreamer/tensor_decoder/tensordec-flexbuf.cc
  ext/nnstreamer/tensor_decoder/tensordec-imagelabel.c
  ext/nnstreamer/tensor_decoder/tensordec-imagesegment.c
  ext/nnstreamer/tensor_decoder/tensordec-pose.c
  ext/nnstreamer/tensor_decoder/tensordec-protobuf.cc
  ext/nnstreamer/tensor_filter/tensor_filter_armnn.cc
  ext/nnstreamer/tensor_filter/tensor_filter_caffe2.cc
  ext/nnstreamer/tensor_filter/tensor_filter_cpp.cc
  ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
  ext/nnstreamer/tensor_filter/tensor_filter_lua.cc
  ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc
  ext/nnstreamer/tensor_filter/tensor_filter_movidius_ncsdk2.c
  ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
  ext/nnstreamer/tensor_filter/tensor_filter_openvino.cc
  ext/nnstreamer/tensor_filter/tensor_filter_python3.cc
  ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc
  ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite.cc
  ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc
  ext/nnstreamer/tensor_filter/vivante/tensor_filter_subplugin.c
  ext/nnstreamer/tensor_source/tensor_src_tizensensor.c
  gst/nnstreamer/nnstreamer_subplugin.c
  gst/nnstreamer/tensor_filter/tensor_filter_custom.c
  gst/nnstreamer/tensor_filter/tensor_filter_custom_easy.c
  tests/cpp_methods/cppfilter_test.cc
  tests/tizen_sensor/dummy_sensor.c
  tools/development/nnstreamerCodeGenCustomFilter.py
Labels: PR/Ready2Go, trivial

#3027 [Tools/Parser] GST Object Emulators
  tools/development/parser/grammar.y
  tools/development/parser/types.c
  tools/development/parser/types.h
Labels: PR/Ready2Go

#3210 [Common] predefined mime type
  gst/nnstreamer/tensor_aggregator/tensor_aggregator.c
  gst/nnstreamer/tensor_common.c
  gst/nnstreamer/tensor_demux/gsttensordemux.c
  gst/nnstreamer/tensor_split/gsttensorsplit.c
  gst/nnstreamer/tensor_transform/tensor_transform.c
Labels: PR/Ready2Go

#3211 [Sink] accept flex tensor
  gst/nnstreamer/tensor_sink/tensor_sink.c
Labels: PR/Ready2Go

#3215 [filter/TVM] Add tensor-filter subplugin for TVM
  ext/nnstreamer/tensor_filter/meson.build
  ext/nnstreamer/tensor_filter/tensor_filter_tvm.cc
  meson.build
  meson_options.txt
Labels: PR/Ready2Go
