Repository nnstreamer/nnstreamer, pull requests merged in 2022-01, with the labels that each got.

#3625 [TEST] Wait for the server to start and fix comment.
  tests/nnstreamer_query/runTest.sh
Labels: trivial

#3632 [fix/bug] Fix destructor of cpp class subplugin
  ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
  ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
  gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
Labels: PR/Ready2Go

#3633 [For LTS branch][fix/bug] Fix destructor of cpp class subplugin
  ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc
  ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
  gst/nnstreamer/tensor_filter/tensor_filter_support_cc.cc
Labels: RELEASE CRITICAL, Tizen 6.5 M2

#3638 [Doc] Update debuild guide.
  Documentation/getting-started-ubuntu-debuild.md
Labels: trivial

#3644 [Spec] Enable SNPE filter on DA profile
  packaging/nnstreamer.spec
Labels: Tizen 6.5 M2
