Repository nnstreamer/nnstreamer, pull requests merged in 2022-04, with the labels that each got.

#3725 [README] Fix daily build log link
  README.md
Labels: trivial

#3718 [lts/6.5][fix/snpe] Handle zero dim models
  ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
Labels: DO NOT MERGE

#3731 [Doc] Change CI server domain name @open sesame 04/20 11:03
  Documentation/API-reference.md
  Documentation/component-description.md
  Documentation/writing-subplugin-tensor-filter.md
  README.md
  gst/nnstreamer/tensor_query/README.md
  jni/README.md
Labels: trivial

#3722 Start Development of NNStreamer 2.1.1 (2.2 RC2) @open sesame 4/14 19:28
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go
