Repository nnstreamer/nnstreamer, pull requests merged in 2022-07, with the labels that each got.

#3816 [gRPC/Common] Modify hard-coded strings indicating sub-plugins' names @open sesame 07/01 20:05
  ext/nnstreamer/extra/nnstreamer_grpc_common.cc
Labels: lts

#3817 [Tests/gRPC] Prepare a fallback value for PATH_TO_PLUGIN @open sesame 07/01 13:45
  tests/nnstreamer_grpc/runTest.sh
Labels: lts

#3828 doc/API-reference: elaborate the document.
  Documentation/API-reference.md
Labels: trivial

#3825 [tests/gRPC] Revise runTest.sh in a more portable way by using the SSAT API
  tests/nnstreamer_grpc/runTest.sh
Labels: lts

#3820 [Tests/Query] Revise runTest.sh to support macOS
  tests/nnstreamer_query/runTest.sh
Labels: lts

#3830 [Tests] Remove unnecessary line feeds in the runTest.sh files @open sesame 07/07 14:15
  tests/codegen/runTest.sh
  tests/nnstreamer_converter/runTest.sh
  tests/nnstreamer_converter_python3/runTest.sh
  tests/nnstreamer_decoder/runTest.sh
  tests/nnstreamer_decoder_boundingbox/runTest.sh
  tests/nnstreamer_decoder_image_labeling/runTest.sh
  tests/nnstreamer_decoder_image_segment/runTest.sh
  tests/nnstreamer_decoder_pose/runTest.sh
  tests/nnstreamer_demux/runTest.sh
  tests/nnstreamer_filter_caffe2/runTest.sh
  tests/nnstreamer_filter_custom/runTest.sh
  tests/nnstreamer_filter_deepview_rt/runTest.sh
  tests/nnstreamer_filter_lua/runTest.sh
  tests/nnstreamer_filter_python3/runTest.sh
  tests/nnstreamer_filter_pytorch/runTest.sh
  tests/nnstreamer_filter_reload/runTest.sh
  tests/nnstreamer_filter_tensorflow/runTest.sh
  tests/nnstreamer_filter_tensorflow2_lite/runTest.sh
  tests/nnstreamer_filter_tensorflow_lite/runTest.sh
  tests/nnstreamer_filter_tensorrt/runTest.sh
  tests/nnstreamer_merge/runTest.sh
  tests/nnstreamer_mux/runTest.sh
  tests/nnstreamer_query/runTest.sh
  tests/nnstreamer_rate/runTest.sh
  tests/nnstreamer_repo/runTest.sh
  tests/nnstreamer_repo_dynamicity/runTest.sh
  tests/nnstreamer_repo_lstm/runTest.sh
  tests/nnstreamer_repo_rnn/runTest.sh
  tests/nnstreamer_sparse/runTest.sh
  tests/nnstreamer_split/runTest.sh
  tests/transform_arithmetic/runTest.sh
  tests/transform_clamp/runTest.sh
  tests/transform_dimchg/runTest.sh
  tests/transform_stand/runTest.sh
  tests/transform_transpose/runTest.sh
  tests/transform_typecast/runTest.sh
Labels: trivial

#3818 [Tests/Meson] Copy bmp2png to the tests directory every build time @open sesame 07/05 10:15
  tests/meson.build
Labels: PR/Ready2Go

#3835 [Refactoring] Apply test fixture to TVM unit test @open sesame 07/14 09:25
  tests/nnstreamer_filter_tvm/unittest_filter_tvm.cc
Labels: PR/Ready2Go

#3833 doc/component-description updates
  Documentation/API-reference.md
  Documentation/component-description.md
Labels: PR/Ready2Go, trivial

#3839 doc/edge-ai: update documentation @open sesame 07/15 11:22
  Documentation/edge-ai.md
Labels: PR/Ready2Go, trivial

#3841 doc/distro-features: update features per distro @open sesame 7/18 16:57
  Documentation/features-per-distro.md
Labels: trivial
