Repository nnstreamer/nnstreamer, pull requests merged in 2022-05, with the labels that each got.

#3710 [Edge] header for nns-edge
  debian/nnstreamer-core.install
  gst/nnstreamer/tensor_query/meson.build
  gst/nnstreamer/tensor_query/nnstreamer_edge.h
  gst/nnstreamer/tensor_query/nnstreamer_edge_aitt.c
  gst/nnstreamer/tensor_query/nnstreamer_edge_common.c
  gst/nnstreamer/tensor_query/nnstreamer_edge_common.h
  gst/nnstreamer/tensor_query/nnstreamer_edge_internal.c
  meson.build
  meson_options.txt
  packaging/nnstreamer.spec
Labels: discussion

#3729 [filter/snpe] Make the order of output tensors be consistent with the user given option @open sesame 4/28 09:30
  ext/nnstreamer/tensor_filter/tensor_filter_snpe.cc
Labels: PR/Ready2Go

#3764 [Conf] fix param name
  gst/nnstreamer/nnstreamer_conf.c
Labels: PR/Ready2Go, trivial
