Repository nnstreamer/nnstreamer, pull requests merged in 2022-09, with the labels that each got.

#3899 [Edge] Update changed flag @open sesame 09/15 10:36
  gst/nnstreamer/tensor_query/tensor_query_client.c
  gst/nnstreamer/tensor_query/tensor_query_server.c
Labels: PR/Ready2Go

#3909 Edge: allow edgesrc/sink in Tizen @open sesame 9/22 20:08
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL, Tizen 7.0 M2

#3905 [EDGE] Support AITT as connection type. @open sesame 09/21 17:21
  gst/edge/edge_common.c
  gst/edge/edge_sink.c
  gst/edge/edge_sink.h
  gst/edge/edge_src.c
  gst/edge/edge_src.h
  meson.build
  meson_options.txt
  packaging/nnstreamer.spec
  tests/nnstreamer_edge/edge/runTest.sh
  tests/nnstreamer_edge/edge/unittest_edge.cc
  tests/nnstreamer_edge/query/unittest_query.cc
  tests/unittest_util.c
  tests/unittest_util.h
Labels: PR/Ready2Go, RELEASE CRITICAL, Tizen 7.0 M2

#3920 [Spec] dependency to nns-edge
  packaging/nnstreamer.spec
Labels: RELEASE CRITICAL, Tizen 7.0 M2

#3908 [Edge] Support MQTT-hybrid connection @open sesame 9/20 11:17
  gst/edge/edge_common.c
  gst/edge/edge_sink.c
  gst/edge/edge_src.c
  tests/nnstreamer_edge/edge/runTest.sh
Labels: RELEASE CRITICAL, Tizen 7.0 M2

#3916 Release of 2.2.0, the new LTS for 2022 (Wait4 #3905 #3908 #3909)
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: Tizen 7.0 M2

#3921 Start of 2.3.0, the new unstable devel version for 2023
  CHANGES
  debian/changelog
  jni/nnstreamer.mk
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go

#3918 [Test] Unittest for filter shared key (Rebased #3458)
  tests/meson.build
  tests/nnstreamer_filter_shared_model/unittest_filter_shared_model.cc
Labels: PR/Ready2Go
