Repository nnstreamer/nnstreamer, pull requests merged in 2023-04, with the labels that each got.

#4042 [EDGE] Add MQTT data transmission test @open sesame 04/20 12:55
  gst/edge/edge_common.c
  tests/nnstreamer_edge/edge/runTest.sh
Labels: PR/Ready2Go, Tizen 7.5 M1

#4041 [datareposrc] Add is-shuffle property
  gst/datarepo/gstdatareposrc.c
  gst/datarepo/gstdatareposrc.h
Labels: PR/Ready2Go, Tizen 7.5 M1

#4063 [API][tensor_trainer] Change type of structure member variable
  gst/nnstreamer/elements/gsttensor_trainer.c
  gst/nnstreamer/include/nnstreamer_plugin_api_trainer.h
Labels: PR/Ready2Go, Tizen 7.5 M1

#4044 [datareposrc] Add json property
  .github/workflows/macos.yaml
  .github/workflows/risc-v.yml
  .github/workflows/ubuntu_clean_meson_build.yml
  debian/control
  gst/datarepo/gstdatareposrc.c
  gst/datarepo/gstdatareposrc.h
  gst/datarepo/meson.build
  meson.build
  packaging/nnstreamer.spec
Labels: PR/Ready2Go, Tizen 7.5 M1

#4049 [datareposrc] Add tensor-sequence property @open sesame 4/21 16:51
  gst/datarepo/gstdatareposrc.c
  gst/datarepo/gstdatareposrc.h
Labels: Tizen 7.5 M1

#4061 [TEST] Add TC for datarepo and tensor_trainer validation
  tests/meson.build
  tests/nnstreamer_datarepo/unittest_datareposink.cc
  tests/nnstreamer_datarepo/unittest_datareposrc.cc
  tests/nnstreamer_trainer/unittest_trainer.cc
  tests/test_models/data/datarepo/mnist.data
  tests/test_models/data/datarepo/mnist.ini
  tests/test_models/data/datarepo/mnist.json
Labels: Tizen 7.5 M1

#4069 [Tizen] Exclude test files for SAM
  .ahub/sam/exclude.txt
Labels: PR/Ready2Go, trivial
