Repository nnstreamer/nnstreamer, pull requests merged in 2024-10, with the labels that each got.

#4589 [tensor_trainer] Remove flexible CAPS from src pad
  gst/nnstreamer/elements/gsttensor_trainer.c
Labels: Need Review

#4607 [Spec] Enable protobuf filter for Movable project
  packaging/nnstreamer.spec
Labels: Tizen 9.0 M2

#4576 [tensor_trainer] Refactoring the chain function
  gst/nnstreamer/elements/gsttensor_trainer.c
  gst/nnstreamer/elements/gsttensor_trainer.h
Labels: PR/Ready2Go

#4614 [datareposink] Code clean, refactoring and bug fix
  gst/datarepo/gstdatareposink.c
Labels: PR/Ready2Go
