Repository nnstreamer/nnstreamer, pull requests merged in 2025-02, with the labels that each got.

#4685 [Action] Fix `NNStreamer + NNTrainer gbs build daily test`
  .github/workflows/update_gbs_cache.yml
Labels: bug

#4686 [Action] action/upload-artifact version update
  .github/workflows/ubuntu_clean_llvm_build.yml
  .github/workflows/ubuntu_clean_meson_build.yml
Labels: build/CI

#4687 [Action/Yocto] Give input for manual trigerring
  .github/workflows/yocto.yml
Labels: PR/Ready2Go

#4688 [Decoder] destructor of decode subplugin
  ext/nnstreamer/tensor_decoder/tensordec-pose.c
Labels: trivial
